"""Build a standalone Stash.exe with PyInstaller.

    python.exe scripts/build_exe.py                 # build
    python.exe scripts/build_exe.py --outdir D:\\apps

Produces a one-folder app (~250 MB, mostly Qt) that runs on a machine with no
Python installed — hand someone the folder and they double-click the .exe.

Two things are easy to get wrong and are handled here:

* the source folder is usually a UNC path (\\\\wsl.localhost\\...), and
  PyInstaller's work/dist directories must NOT live there — it writes
  constantly and UNC makes that slow and lock-prone. Both default to a local
  temp/output path.
* imageio_ffmpeg's bundled ffmpeg.exe is data, not an import, so PyInstaller
  cannot discover it. It is added explicitly.
"""

from __future__ import annotations

import argparse
import os
import shlex
import subprocess
import sys
import tempfile
from pathlib import Path

APP_NAME = "Stash"
PUBLISHER = "Amreet Khuntia"
# ASCII only: PyInstaller reads the generated --version-file itself, and its
# decoding of non-ASCII has been inconsistent across releases. Not worth an
# em dash.
DESCRIPTION = "Stash - searchable media library"

PLUGIN_DIR = Path(__file__).resolve().parent.parent
BUILD_REQUIREMENTS = PLUGIN_DIR / "requirements-build.txt"

# The Windows file-properties resource. PyInstaller evals this file, so it is
# Python source rather than a data format. 0x40004 is VOS_NT_WINDOWS32 and
# fileType 0x1 is VFT_APP; the four-integer version is a Win32 requirement,
# which is why stashlib/_version.py is restricted to X.Y.Z.
VERSIONINFO = """\
# Generated by scripts/build_exe.py. Do not edit; edit stashlib/_version.py.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={parts}, prodvers={parts},
    mask=0x3f, flags=0x0, OS=0x40004, fileType=0x1, subtype=0x0, date=(0, 0)
  ),
  kids=[
    StringFileInfo([StringTable('040904B0', [
      StringStruct('CompanyName', {publisher!r}),
      StringStruct('FileDescription', {description!r}),
      StringStruct('FileVersion', {version!r}),
      StringStruct('InternalName', {name!r}),
      StringStruct('LegalCopyright', {copyright!r}),
      StringStruct('OriginalFilename', {filename!r}),
      StringStruct('ProductName', {name!r}),
      StringStruct('ProductVersion', {version!r}),
    ])]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""


def _default_outdir() -> Path:
    base = os.environ.get("LOCALAPPDATA") or tempfile.gettempdir()
    return Path(base) / "Stash" / "build"


def app_version() -> str:
    """The version from stashlib/_version.py — the only place it lives."""
    sys.path.insert(0, str(PLUGIN_DIR))
    from stashlib._version import __version__

    return __version__


def write_version_resource(workdir: Path, version: str) -> Path:
    """Write the VERSIONINFO PyInstaller needs for --version-file.

    Into workdir, never the repo: it is derived from _version.py, so a copy
    under version control would be one more thing that can disagree.
    """
    numbers = tuple(int(part) for part in version.split("."))
    workdir.mkdir(parents=True, exist_ok=True)
    target = workdir / "version_info.txt"
    target.write_text(
        VERSIONINFO.format(
            parts=numbers + (0,) * (4 - len(numbers)),
            version=version,
            name=APP_NAME,
            filename=f"{APP_NAME}.exe",
            publisher=PUBLISHER,
            description=DESCRIPTION,
            copyright=f"Copyright (C) {PUBLISHER}",
        ),
        encoding="utf-8",
    )
    return target


def sign_argv(command: str, target: Path) -> list[str]:
    """Turn a --sign-command string into an argv list for `target`.

    The same string is handed to Inno Setup as a SignTool, where ``$f`` is the
    placeholder for the file being signed. Honour that convention here so one
    command works in both places; append the path only when there is no
    placeholder to substitute.

    posix=False keeps Windows backslashes intact -- shlex's posix mode would
    eat them as escapes and turn C:\\certs\\x.pfx into C:certsx.pfx -- at the
    cost of leaving quotes on the tokens, which are stripped after the fact.
    """
    tokens = [
        token[1:-1] if len(token) > 1 and token[0] == token[-1] == '"' else token
        for token in shlex.split(command, posix=False)
    ]
    if any("$f" in token for token in tokens):
        return [token.replace("$f", str(target)) for token in tokens]
    return tokens + [str(target)]


def ensure_pyinstaller(auto_install: bool = True) -> bool:
    try:
        import PyInstaller  # noqa: F401

        return True
    except ImportError:
        pass
    if not auto_install:
        print(f"PyInstaller is not installed. pip install -r {BUILD_REQUIREMENTS}")
        return False
    # The pinned spec, not a bare `pyinstaller`: an unpinned build tool means a
    # PyInstaller release can break the installer with no commit of ours.
    print("PyInstaller is not installed — installing the pinned version now...")
    spec = ["-r", str(BUILD_REQUIREMENTS)] if BUILD_REQUIREMENTS.exists() else ["pyinstaller"]
    result = subprocess.run(
        [sys.executable, "-m", "pip", "install", "--disable-pip-version-check", *spec]
    )
    return result.returncode == 0


def ffmpeg_binary() -> Path | None:
    try:
        import imageio_ffmpeg

        return Path(imageio_ffmpeg.get_ffmpeg_exe())
    except Exception:
        return None


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--outdir", type=Path, default=None, help="where to put the app")
    parser.add_argument("--onefile", action="store_true", help="single .exe (slower start)")
    parser.add_argument("--app-version", default=None,
                        help="override the version (default: stashlib/_version.py)")
    parser.add_argument("--no-auto-install", action="store_true",
                        help="fail instead of pip-installing PyInstaller (CI)")
    parser.add_argument("--sign-command", default=None,
                        help="sign the built Stash.exe with this; $f is the file, "
                             "or it is appended if you leave $f out")
    args = parser.parse_args()

    if not ensure_pyinstaller(auto_install=not args.no_auto_install):
        print("Could not install PyInstaller.")
        return 1

    plugin_dir = PLUGIN_DIR
    entry = plugin_dir / "panel" / "__main__.py"
    icon = plugin_dir / "panel" / "icon.ico"
    style = plugin_dir / "panel" / "style.qss"

    outdir = (args.outdir or _default_outdir()).resolve()
    workdir = outdir / "work"
    outdir.mkdir(parents=True, exist_ok=True)

    separator = ";" if os.name == "nt" else ":"
    command = [
        sys.executable, "-m", "PyInstaller",
        "--noconfirm",
        "--clean",
        "--windowed",  # no console window
        "--name", APP_NAME,
        "--distpath", str(outdir / "dist"),
        "--workpath", str(workdir),
        "--specpath", str(workdir),
        "--paths", str(plugin_dir),
        # style.qss is read at runtime from next to panel/, so it must ship.
        "--add-data", f"{style}{separator}panel",
        # Qt multimedia is loaded through plugins PyInstaller does not always see.
        "--hidden-import", "PySide6.QtMultimedia",
        "--hidden-import", "PySide6.QtMultimediaWidgets",
        "--hidden-import", "win32com.client",
        # Trim the biggest things nothing here uses.
        "--exclude-module", "PySide6.QtWebEngineCore",
        "--exclude-module", "PySide6.QtWebEngineWidgets",
        "--exclude-module", "PySide6.Qt3DCore",
        "--exclude-module", "matplotlib",
        "--exclude-module", "tkinter",
    ]
    if args.onefile:
        command.append("--onefile")
    if icon.exists():
        command += ["--icon", str(icon)]

    version = args.app_version or app_version()
    if os.name == "nt":
        # A Windows-only resource — right-click > Properties > Details. Skipped
        # elsewhere so this script stays runnable (if useless) from WSL.
        command += ["--version-file", str(write_version_resource(workdir, version))]

    ffmpeg = ffmpeg_binary()
    if ffmpeg and ffmpeg.exists():
        command += ["--add-binary", f"{ffmpeg}{separator}imageio_ffmpeg/binaries"]
    else:
        print("warning: imageio_ffmpeg binary not found — video thumbnails will not work")

    command.append(str(entry))

    print(f"building {APP_NAME} {version} -> {outdir / 'dist'}")
    result = subprocess.run(command)
    if result.returncode != 0:
        print("\nBuild failed. The output above says why.")
        return result.returncode

    app = outdir / "dist" / APP_NAME

    if args.sign_command:
        # Sign the app itself, not just the installer. A signed Setup.exe that
        # lays down an unsigned Stash.exe still trips SmartScreen on launch.
        print("=== signing the app ===")
        signed = subprocess.run(sign_argv(args.sign_command, app / f"{APP_NAME}.exe"))
        if signed.returncode != 0:
            print("\nSigning failed.")
            return signed.returncode

    print(f"\nBuilt: {app}")
    print(f"Run:   {app / (APP_NAME + '.exe')}")
    print("\nHand the whole folder to someone — no Python needed on their machine.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
